M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu24.04.1 date 2026-09-16T15:22:34
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-16T15:22:34-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X81.7Y-119.7
X81.7Y-123.9
T2
X72.4Y-106.4
X72.4Y-145.6
X147.6Y-106.4
X147.6Y-145.6
M30
